env:
  node: true
parser: "@typescript-eslint/parser"
extends:
  - "plugin:@typescript-eslint/recommended"
  - "prettier/@typescript-eslint"
  - "plugin:prettier/recommended"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: tsconfig.json
rules:
  "@typescript-eslint/interface-name-prefix": [error, never]
  "@typescript-eslint/promise-function-async": warn
  "@typescript-eslint/explicit-function-return-type": off
overrides:
  - files: ["src/**/*.test.ts"]
    env:
      node: true
      jest: true
